{% set name = "pyretis" %}
{% set version = "2.0.3" %}
{% set sha256 = "7f2367fe031c8c9623527e9de8c76de32ae2d865453b9797fe7a62209fba066e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py2k]
  
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
  
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - zlib
    - msinttypes  # [win and py27]
    - mdtraj
    
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - pytables
    - zlib 1.2.11
    - colorama
    - tqdm
    - docutils
    - matplotlib
    - jinja2
    - mdtraj

test:
  imports:
    - pyretis

about:
  home: http://www.pyretis.org
  license: LGPLv2.1+
  summary: 'PyRETIS: A well-done, medium-sized python library for rare events, DOI: 10.1002/jcc.24900'

extra:
  recipe-maintainers:
    - EnricoRiccardi
    - andersle
    - sroet
