appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hhnaSN4C3Iq54vLm5SbPMicX+COvb/tQUAYjgEQHYgViy+WGo07npB2doV7NVT8ZI4JZq9+97R8Jq9TNeykM2zyutipqp/84tBFyDTsavAWI2wBvowKF2WGH9MCZQzBpzB2HE1YxjmCIl/tqdZMHK8t0eVyWJrh/dLL/Bw6aYin67267BPF4fdixXFy2NLKxZDxXZlZrNgZV3I/zlinEEToC6EKh2XkbU+qc+sVkRwcDCuAScIe448iM66OxpQ2Zmsk1hyglyCjcyU4KL4EZsWVcm3f9w8qx+wbg7sE9tYNxIdJEnqgkCsSew+V/L0N9ZDNIuUyOWWuKDySPTiHvjqSCTBNSPxdscn/MFif3i3/TntTQdC7Vpx2XwAhHoHg8qPKSmzzuEtsguxtSUsghSIjkZS/lStvDbS6WKugOOOk9RK3ZQMidvhclJP3UAgsJ7xnQO10aWbwJDrzb8+3+O3sNGFFFfbE4O82KfDT3c9Eh8mB+6z33hr85Fn17KlL2vDScA4q9Na0O4QWLjBLx8+y13xTfGVAGAfTj5ph6BIXm0HHgajeGdt+1vfRhKN920213NAhuNF3BUns0QeOy+CO7b/t/7mzbcxoTrvqcKaOP1CzkYQCZ0C5winoZiAq9oMdBkim2fzZr9/f0VKFqRcT3QCnCOfdUeH147dJNb1M=}
